# 2023-03-26 18:30:29
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans D:\KaldeniaServer\Server\Network\NetState.cs:ligne 813


# 2023-03-29 21:35:27
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans D:\KaldeniaServer\Server\Network\NetState.cs:ligne 813


# 2023-04-01 17:24:24
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans D:\KaldeniaServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans D:\KaldeniaServer\Server\Network\NetState.cs:ligne 598


# 2023-04-01 17:24:24
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans D:\KaldeniaServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans D:\KaldeniaServer\Server\Network\NetState.cs:ligne 598


# 2023-04-02 23:40:40
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans D:\KaldeniaServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans D:\KaldeniaServer\Server\Network\NetState.cs:ligne 598


# 2023-04-03 04:28:08
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans D:\KaldeniaServer\Server\Network\NetState.cs:ligne 813


# 2023-04-22 03:58:25
System.Net.Sockets.SocketException (0x80004005): Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-04-22 12:47:53
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-22 12:47:53
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-04-22 12:47:53
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-04-22 12:47:53
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-04-22 12:47:53
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-04-22 12:47:53
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-04-22 12:47:53
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-22 12:47:53
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-04-22 12:47:53
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-04-22 12:47:53
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-22 12:47:53
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-04-22 12:47:53
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-04-22 12:47:53
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-04-22 12:47:53
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-04-22 12:47:53
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-04-22 12:47:53
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-22 12:47:53
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-04-22 12:47:53
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-04-22 12:47:53
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-22 12:47:53
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-22 12:47:53
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-22 12:47:53
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-24 16:50:30
System.Net.Sockets.SocketException (0x80004005): Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-04-24 22:54:51
System.Net.Sockets.SocketException (0x80004005): Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-04-24 23:02:14
System.Net.Sockets.SocketException (0x80004005): Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-04-25 14:19:04
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-04-26 22:19:12
System.Net.Sockets.SocketException (0x80004005): Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-04-27 02:21:49
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-04-28 14:20:54
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-28 14:20:55
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-28 14:20:55
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-28 14:20:55
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-28 14:20:55
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-28 14:20:55
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-28 14:20:55
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-28 14:20:55
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-28 14:20:55
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-28 14:20:55
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-28 14:20:55
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-28 14:20:55
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-28 14:20:55
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-28 14:20:55
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-04-28 14:20:55
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-28 14:20:55
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-30 11:30:44
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-30 11:30:44
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-30 11:30:44
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-30 11:30:44
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-30 11:30:44
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-30 11:30:44
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-30 11:30:44
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-30 11:30:44
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-30 11:30:44
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-30 11:30:44
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-30 11:30:44
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-30 11:30:44
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-30 11:30:44
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-30 11:30:44
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-30 11:30:44
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-30 11:30:44
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-04-30 11:30:44
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-05-02 19:31:52
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-05-03 17:19:45
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-05-04 16:46:41
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-05-05 06:41:00
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-05-05 12:40:41
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-05-12 16:17:34
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-05-14 15:11:04
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.OnSend(IAsyncResult asyncResult) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 716


# 2023-05-14 16:27:27
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-05-14 16:28:15
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-05-14 18:01:20
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-05-14 19:14:35
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.OnSend(IAsyncResult asyncResult) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 716


# 2023-05-14 22:12:13
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-05-14 23:05:08
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-05-15 02:04:02
System.ObjectDisposedException: Le handle sécurisé a été fermé
   à System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   à System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   à System.Net.UnsafeNclNativeMethods.OSSOCK.WSASend(SafeCloseSocket socketHandle, WSABuffer& buffer, Int32 bufferCount, Int32& bytesTransferred, SocketFlags socketFlags, SafeHandle overlapped, IntPtr completionRoutine)
   à System.Net.Sockets.Socket.DoBeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, OverlappedAsyncResult asyncResult)
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-05-15 23:25:22
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-05-16 03:29:35
System.ObjectDisposedException: Impossible d'accéder à un objet supprimé.
Nom de l'objet : 'System.Net.Sockets.Socket'.
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-05-16 16:07:46
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-05-17 01:02:25
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-05-17 07:10:15
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-05-17 23:35:49
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-05-18 02:03:22
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-05-21 07:51:40
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-05-22 10:01:14
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-05-22 15:22:39
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-05-23 01:29:11
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 01:40:33
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.OnReceive(IAsyncResult asyncResult) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 658


# 2023-05-23 01:41:59
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 01:42:05
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 01:42:09
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 01:42:39
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 01:45:14
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 01:45:41
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 02:23:14
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 02:23:50
System.ObjectDisposedException: Le handle sécurisé a été fermé
   à System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   à System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   à System.Net.UnsafeNclNativeMethods.OSSOCK.WSARecv(SafeCloseSocket socketHandle, WSABuffer& buffer, Int32 bufferCount, Int32& bytesTransferred, SocketFlags& socketFlags, SafeHandle overlapped, IntPtr completionRoutine)
   à System.Net.Sockets.Socket.DoBeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, OverlappedAsyncResult asyncResult)
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.OnReceive(IAsyncResult asyncResult) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 658


# 2023-05-23 02:27:37
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 02:28:14
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 02:29:43
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 02:31:00
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 02:31:22
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 02:33:27
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 02:33:36
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 02:35:04
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 02:37:20
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 02:42:16
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 02:43:16
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 02:47:19
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 02:47:57
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 02:48:01
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 02:49:44
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 02:50:56
System.ObjectDisposedException: Le handle sécurisé a été fermé
   à System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   à System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   à System.Net.UnsafeNclNativeMethods.OSSOCK.WSARecv(SafeCloseSocket socketHandle, WSABuffer& buffer, Int32 bufferCount, Int32& bytesTransferred, SocketFlags& socketFlags, SafeHandle overlapped, IntPtr completionRoutine)
   à System.Net.Sockets.Socket.DoBeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, OverlappedAsyncResult asyncResult)
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.OnReceive(IAsyncResult asyncResult) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 658


# 2023-05-23 02:57:05
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:00:00
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:01:58
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:02:21
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:04:09
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:04:14
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:04:35
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:05:14
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:07:19
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:08:03
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.OnReceive(IAsyncResult asyncResult) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 658


# 2023-05-23 03:08:40
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:08:42
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:10:14
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:10:44
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:12:23
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:12:48
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:17:10
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:17:12
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:18:23
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:21:26
System.ObjectDisposedException: Le handle sécurisé a été fermé
   à System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   à System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   à System.Net.UnsafeNclNativeMethods.OSSOCK.WSARecv(SafeCloseSocket socketHandle, WSABuffer& buffer, Int32 bufferCount, Int32& bytesTransferred, SocketFlags& socketFlags, SafeHandle overlapped, IntPtr completionRoutine)
   à System.Net.Sockets.Socket.DoBeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, OverlappedAsyncResult asyncResult)
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.OnReceive(IAsyncResult asyncResult) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 658


# 2023-05-23 03:23:17
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:27:15
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:28:27
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:31:23
System.ObjectDisposedException: Le handle sécurisé a été fermé
   à System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   à System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   à System.Net.UnsafeNclNativeMethods.OSSOCK.WSARecv(SafeCloseSocket socketHandle, WSABuffer& buffer, Int32 bufferCount, Int32& bytesTransferred, SocketFlags& socketFlags, SafeHandle overlapped, IntPtr completionRoutine)
   à System.Net.Sockets.Socket.DoBeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, OverlappedAsyncResult asyncResult)
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.OnReceive(IAsyncResult asyncResult) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 658


# 2023-05-23 03:31:29
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:32:02
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:33:59
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:34:40
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:38:39
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:39:50
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:40:12
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:40:25
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:44:29
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:44:30
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:46:25
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:48:43
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:49:22
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:52:02
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:52:26
System.ObjectDisposedException: Le handle sécurisé a été fermé
   à System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   à System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   à System.Net.UnsafeNclNativeMethods.OSSOCK.WSARecv(SafeCloseSocket socketHandle, WSABuffer& buffer, Int32 bufferCount, Int32& bytesTransferred, SocketFlags& socketFlags, SafeHandle overlapped, IntPtr completionRoutine)
   à System.Net.Sockets.Socket.DoBeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, OverlappedAsyncResult asyncResult)
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.OnReceive(IAsyncResult asyncResult) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 658


# 2023-05-23 03:53:41
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 03:56:26
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:00:29
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:01:17
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:04:12
System.Net.Sockets.SocketException (0x80004005): Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.OnReceive(IAsyncResult asyncResult) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 658


# 2023-05-23 04:04:46
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:06:47
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:07:48
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:11:34
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:13:39
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:16:15
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:17:44
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:19:04
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:19:14
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:19:42
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:20:55
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:21:33
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:22:45
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:22:46
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:23:01
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:27:15
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:29:53
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:30:50
System.ObjectDisposedException: Le handle sécurisé a été fermé
   à System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   à System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   à System.Net.UnsafeNclNativeMethods.OSSOCK.WSARecv(SafeCloseSocket socketHandle, WSABuffer& buffer, Int32 bufferCount, Int32& bytesTransferred, SocketFlags& socketFlags, SafeHandle overlapped, IntPtr completionRoutine)
   à System.Net.Sockets.Socket.DoBeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, OverlappedAsyncResult asyncResult)
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.OnReceive(IAsyncResult asyncResult) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 658


# 2023-05-23 04:31:07
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:32:48
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:35:17
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:35:52
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:36:44
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:37:00
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:39:52
System.Net.Sockets.SocketException (0x80004005): Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.OnReceive(IAsyncResult asyncResult) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 658


# 2023-05-23 04:44:40
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:47:46
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:49:33
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.OnReceive(IAsyncResult asyncResult) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 658


# 2023-05-23 04:49:50
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:54:36
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 04:59:19
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 05:02:29
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 05:04:18
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 05:04:46
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 05:06:22
System.Net.Sockets.SocketException (0x80004005): Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.OnReceive(IAsyncResult asyncResult) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 658


# 2023-05-23 05:06:36
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-05-23 05:07:22
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 05:09:05
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 05:09:21
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 05:10:41
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 05:12:31
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 05:13:21
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 05:13:59
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 05:17:26
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 05:18:17
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 05:21:35
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 05:21:38
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 05:22:32
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 05:22:39
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 05:23:07
System.Net.Sockets.SocketException (0x80004005): Une connexion établie a été abandonnée par un logiciel de votre ordinateur hôte
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.OnReceive(IAsyncResult asyncResult) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 658


# 2023-05-23 05:23:35
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 05:23:48
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 05:26:33
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 05:27:28
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 05:27:39
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 05:30:28
System.Net.Sockets.SocketException (0x80004005): Un argument non valide a été fourni
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-05-23 17:08:46
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-05-24 12:25:24
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-05-27 16:18:06
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-05-28 22:32:41
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-05-29 17:09:46
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-05-29 20:58:39
System.ObjectDisposedException: Le handle sécurisé a été fermé
   à System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   à System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   à System.Net.UnsafeNclNativeMethods.OSSOCK.WSASend(SafeCloseSocket socketHandle, WSABuffer& buffer, Int32 bufferCount, Int32& bytesTransferred, SocketFlags socketFlags, SafeHandle overlapped, IntPtr completionRoutine)
   à System.Net.Sockets.Socket.DoBeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, OverlappedAsyncResult asyncResult)
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-05-31 02:10:35
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-05-31 02:10:35
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-05-31 02:14:18
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-05-31 02:14:18
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-06-04 13:04:59
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-06-04 14:11:10
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-06-05 17:28:08
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-06-08 20:17:55
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-06-09 21:08:47
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-06-09 21:08:47
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-06-09 21:08:48
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-06-09 21:08:48
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-06-09 21:08:48
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-06-09 21:08:48
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-06-09 21:08:48
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-06-10 10:52:57
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-06-13 23:05:33
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-06-14 16:04:51
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-06-16 04:15:39
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-06-16 18:20:48
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-06-17 05:26:36
System.ObjectDisposedException: Le handle sécurisé a été fermé
   à System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   à System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   à System.Net.UnsafeNclNativeMethods.OSSOCK.WSASend(SafeCloseSocket socketHandle, WSABuffer& buffer, Int32 bufferCount, Int32& bytesTransferred, SocketFlags socketFlags, SafeHandle overlapped, IntPtr completionRoutine)
   à System.Net.Sockets.Socket.DoBeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, OverlappedAsyncResult asyncResult)
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-06-17 18:21:41
System.ObjectDisposedException: Le handle sécurisé a été fermé
   à System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   à System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   à System.Net.UnsafeNclNativeMethods.OSSOCK.WSASend(SafeCloseSocket socketHandle, WSABuffer& buffer, Int32 bufferCount, Int32& bytesTransferred, SocketFlags socketFlags, SafeHandle overlapped, IntPtr completionRoutine)
   à System.Net.Sockets.Socket.DoBeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, OverlappedAsyncResult asyncResult)
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-06-18 05:32:51
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-06-18 19:08:59
System.ObjectDisposedException: Impossible d'accéder à un objet supprimé.
Nom de l'objet : 'System.Net.Sockets.Socket'.
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-06-19 15:12:56
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-06-21 23:34:05
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   à Server.Network.NetState.Dispose(Boolean flush) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 924


# 2023-07-01 15:41:07
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-01 15:41:07
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-01 15:41:07
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-01 15:41:07
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-01 15:41:07
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-01 15:41:07
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-01 15:41:08
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-01 15:41:08
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-01 15:41:08
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-01 15:41:08
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-02 06:46:15
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-02 09:49:31
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-02 10:02:49
System.ObjectDisposedException: Le handle sécurisé a été fermé
   à System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   à System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   à System.Net.UnsafeNclNativeMethods.OSSOCK.WSASend(SafeCloseSocket socketHandle, WSABuffer& buffer, Int32 bufferCount, Int32& bytesTransferred, SocketFlags socketFlags, SafeHandle overlapped, IntPtr completionRoutine)
   à System.Net.Sockets.Socket.DoBeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, OverlappedAsyncResult asyncResult)
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-07-02 10:05:49
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-04 02:59:55
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.OnSend(IAsyncResult asyncResult) dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 716


# 2023-07-04 19:24:23
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-07-07 13:08:10
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-07 13:08:10
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-07 13:08:10
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-07 13:08:10
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-07 13:08:10
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-07 13:08:10
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-07 13:08:10
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-08 03:29:10
System.ObjectDisposedException: Impossible d'accéder à un objet supprimé.
Nom de l'objet : 'System.Net.Sockets.Socket'.
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-07-08 13:47:05
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-07-09 13:01:46
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-12 01:56:40
System.ObjectDisposedException: Impossible d'accéder à un objet supprimé.
Nom de l'objet : 'System.Net.Sockets.Socket'.
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, SocketError& errorCode, AsyncCallback callback, Object state)
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-07-12 02:58:16
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-07-12 20:51:23
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-07-13 22:24:30
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


# 2023-07-15 20:40:24
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-15 20:40:25
System.Net.Sockets.SocketException (0x80004005): Une connexion existante a dû être fermée par l’hôte distant
   à System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.InternalBeginReceive() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 613
   à Server.Network.NetState.Start() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 598


# 2023-07-24 23:31:31
System.Net.Sockets.SocketException (0x80004005): Une demande d’envoi ou de réception de données n’a pas été autorisée car le socket avait déjà été éteint dans cette direction par un appel d’arrêt précédent
   à System.Net.Sockets.Socket.BeginSend(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)
   à Server.Network.NetState.Flush() dans C:\LeRefuge\LeRefugeServer\Server\Network\NetState.cs:ligne 813


